# Generated by Django 2.2.17 on 2021-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210130_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('MSK', 'Moscow'), ('NY', 'New York'), ('LA', 'Los Angeles'), ('TKO', 'Tokyo')], max_length=24),
        ),
    ]
