# Generated by Django 2.2.17 on 2021-02-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина товаров', 'verbose_name_plural': 'Корзины товаров'},
        ),
    ]
